### ISSUE TITLE
getHistoricalData fields don't match the official ones

### ISSUE THREAD

**Issue by tredondo** [maxicus/ib-tws-api#19]
getHistoricalData returns an undocumented [custom object](https://github.com/maxicus/ib-tws-api/blob/6aff0db1d14742522a3defd7f591e481e590304d/income-fieldset-handlers/index.js#L247-L285) that doesn't match the official [Bar class](https://interactivebrokers.github.io/tws-api/classIBApi_1_1Bar.html).

There are extra .dateStart and .dateEnd fields, and the bars arrive in `.bars`. OK, not so bad. But then each bar renames `time` to `date`, `WAP` to `average` (presumably), and `count` to `barCount`.

What has been the reasoning here?

**Comment by maxicus** [comment]
It was never supposed to mimic Java API, since it has own legacy stuff. And it's very old library (i've used it 10 years ago) and has a lot of legacy burden. They have to.
Particularly it's architecture doesn't support request-response notation, auto reconnect, and many other stuff.

so no reason to use uncommon weird names.
dateStart, dateEnd is a good example - they are in the protocol's response and useful, but not in java api return object.
