### ISSUE TITLE
Incomplete API and misformated js docs

### ISSUE THREAD

**Issue by daniel-brenot** [maxicus/ib-tws-api#6]
The jsdocs are still formatted similar to how they would be in python, so the documentation doesn't show in intellisense. Also the incomplete APIs show in my intellisense, which crouds it when i'm trying to find working APIs.

Less of a complaint and more of an issue for me to attach to a pull request i'm making. Dispite this API being incomplete, the async/await syntax on this is something i've been looking for for a while now, so i'm going to clean up the jsdocs and add typings to the parameters in the jsdocs. I may make other commits to this repo in the future as well.

Great work on this so far, and i'm happy to help going forward!

**Comment by maxicus** [comment]
You are welcome to participate.

Docs is something what is always missing in opensource :)

Tried to compensate that with some examples at least.

**Comment by tredondo** [comment]
@daniel-brenot I would solve that along with a TypeScript conversion (#15).

**Comment by daniel-brenot** [comment]
> @daniel-brenot I would solve that along with a TypeScript conversion (#15).

Would love to, but this guy seems to have some weird aversion to modern tools. If i end up making a typescriot equivalent of the IB library in the future i'll pop back here and mention it.

**Comment by tredondo** [comment]
@daniel-brenot Making a Node IB library is far from easy, and @maxicus has already put a lot of good work into it.

I've started coding in assembly in the 90s and prefer simplicity whenever possible, but I adopted TypeScript because the optional complexity it added, has [paid off](https://www.altexsoft.com/blog/typescript-pros-and-cons/), and the tooling makes working with it seemless now. Mainly, `ts-node` and `ts-jest` allow running, debugging and testing code without compiling to JS (no .js files, no .map files, just pure `.ts`), and with negligible performance penalty.

@maxicus, would it be possible to persuade you about the benefits of TypeScript?
